apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cart-deploy"
  namespace: default
  labels:
    app: "cart-deploy"
spec:
  selector:
    matchLabels:
      app: "cart-deploy"
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "cart-deploy"
    spec:
      containers:
      - name: "cart-deploy"
        image: chukwuderaibe/cart
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 1004
          name: "cart-deploy"


---
apiVersion: v1
kind: Service
metadata:
  name: "cart-service"
  namespace: default
spec:
  selector:
    app: "cart-deploy"
  type: ClusterIP
  ports:
  - name: "cart-depl0y"
    protocol: TCP
    port: 1004
    targetPort: 1004

