apiVersion: apps/v1
kind: Deployment
metadata:
  name: "react-ui"
  namespace: default
  labels:
    app: "react-ui"
spec:
  selector:
    matchLabels:
      app: "react-ui"
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "react-ui"
    spec:
      containers:
      - name: "react-ui"
        image: chukwuderaibe/ui
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: "react-ui"


---
apiVersion: v1
kind: Service
metadata:
  name: "react-ui"
  namespace: default
spec:
  selector:
    app: "react-ui"
  type: NodePort
  ports:
  - name: "react-ui"
    protocol: TCP
    port: 8080
    targetPort: 8080

