apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "react-ui"
  namespace: ms
  labels:
    app:  "react-ui"
spec:
  selector:
    matchLabels:
      app: "react-ui"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  "react-ui"
    spec:
      containers:
      - name:  "react-ui"
        image:  163527433426.dkr.ecr.us-west-1.amazonaws.com/ui:latest
        ports:
        - containerPort:  8089
          name:  "react-ui"

          ---

apiVersion: v1
kind: Service
metadata:
  name: "react-ui"
  namespace: ms
spec:
  selector:
    app: "react-ui"
  type: NodePort
  ports:
  - name: "react-ui"
    protocol: TCP
    port: 8089
    targetPort: 8089