apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zuul-deploy"
  namespace: default
  labels:
    app: "zuul-deploy"
spec:
  selector:
    matchLabels:
      app: "zuul-deploy"
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "zuul-deploy"
    spec:
      containers:
      - name: "zuul-deploy"
        image: chukwuderaibe/offers
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9999
          name: "zuul-deploy"

---
apiVersion: v1
kind: Service
metadata:
  name: "zuul-deploy"
  namespace: default
spec:
  selector:
    app: "zuul-deploy"
  type: NodePort
  ports:
  - name: "zuul-deploy"
    protocol: TCP
    port: 9999
    targetPort: 9999
