apiVersion: apps/v1
kind: Deployment
metadata:
  name: "offers"
  namespace: default
  labels:
    app: "offers"
spec:
  selector:
    matchLabels:
      app: "offers"
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "offers"
    spec:
      containers:
      - name: "offers"
        image: chukwuderaibe/offers
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 1001
          name: "offers"


---
apiVersion: v1
kind: Service
metadata:
  name: "offers"
  namespace: default
spec:
  selector:
    app: "offers"
  type: ClusterIP
  ports:
  - name: "offers"
    protocol: TCP
    port: 1001
    targetPort: 1001
